//************************************************************************
//************************************************************************
//***
//***  NOTE:  This file was automatically generated by MKPINS
//***  Processing Date/Time:     Mon 24-Jun-2019 13:48:40
//***  Input Pin Info CSV file:  pinout.csv
//***  Project Name Prefix:      ZEBRA
//***  Output C-File:            zebra_gpio.c
//***  Output H-File:            zebra_gpio.h
//***
//************************************************************************
//************************************************************************

#include "zebra_gpio.h"

const ZEBRA_PINDEF ZEBRA_PIC_TXD = { 0, 46, 0, 0, "RD1", "TXD3", "SDA1", "PIC_TXD", 1, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_PIC_RXD = { 1, 47, 0, 1, "TD1", "RXD3", "SCL1", "PIC_RXD", 1, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TXD1 = { 2, 98, 0, 2, "TXD0", "N/A", "N/A", "TXD1", 1, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_RXD1 = { 3, 99, 0, 3, "RXD0", "N/A", "N/A", "RXD1", 1, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_IR_SIG = { 4, 81, 0, 4, "I2SRX_CLK", "RD2", "CAP2.0", "IR_SIG", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_ST_LED2 = { 5, 80, 0, 5, "I2SRX_WS", "TD2", "CAP2.1", "ST_LED2", 0, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_ST_LED3 = { 6, 79, 0, 6, "I2SRX_SDA", "SSEL1", "MAT2.0", "ST_LED3", 0, 0, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_ST_LED4 = { 7, 78, 0, 7, "I2STX_CLK", "SCK1", "MAT2.1", "ST_LED4", 0, 0, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_ST_LED5 = { 8, 77, 0, 8, "I2STX_WS", "MISO1", "MAT2.2", "ST_LED5", 0, 0, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_ST_LED6 = { 9, 76, 0, 9, "I2SRTX_SDA", "MOSI1", "MAT2.3", "ST_LED6", 0, 0, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_SDA2 = { 10, 48, 0, 10, "TXD2", "SDA2", "MAT3.0", "SDA2", 2, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SCL2 = { 11, 49, 0, 11, "RXD2", "SCL2", "MAT3.1", "SCL2", 2, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SPI_CLK = { 12, 62, 0, 15, "TXD1", "SCK0", "SCK", "SPI_CLK", 3, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SPI_CSEL = { 13, 63, 0, 16, "RXD1", "SSEL0", "SSEL", "SPI_CSEL", 3, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SPI_MISO = { 14, 61, 0, 17, "CTS1", "MISO0", "MISO", "SPI_MISO", 3, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SPI_MOSI = { 15, 60, 0, 18, "DCD1", "MOSI0", "MOSI", "SPI_MOSI", 3, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SPI_HOLD = { 16, 59, 0, 19, "DSR1", "MCICLK", "SDA1", "SPI_HOLD", 255, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_MCU_RESET_OUT = { 17, 58, 0, 20, "DTR1", "MSICMD", "SCL1", "MCU_RESET_OUT", 255, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_GLOBAL_RESET = { 18, 57, 0, 21, "RI1", "MCIPWR", "RD1", "GLOBAL_RESET", 255, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_PIC_RESET = { 19, 56, 0, 22, "RTS1", "MCIDATA0", "TD1", "PIC_RESET", 0, 255, 0, 1, 1, 1 };
const ZEBRA_PINDEF ZEBRA_MCU_3V3_EN = { 20, 9, 0, 23, "AD0.0", "I2SRX_CLK", "CAP3.0", "MCU_3V3_EN", 0, 0, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_MCU_1V8_EN = { 21, 8, 0, 24, "AD0.1", "I2SRX_WS", "CAP3.1", "MCU_1V8_EN", 0, 0, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_SDA = { 22, 25, 0, 27, "SDA0", "N/A", "N/A", "SDA", 1, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SCL = { 23, 24, 0, 28, "SCL0", "N/A", "N/A", "SCL", 1, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_USB_DP = { 24, 29, 0, 29, "USB_D+1", "N/A", "N/A", "USB_DP", 0, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_USB_DM = { 25, 30, 0, 30, "USB_D-1", "N/A", "N/A", "USB_DM", 0, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_PB0 = { 26, 95, 1, 0, "ENET_TXD0", "N/A", "N/A", "PB0", 0, 1, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_PB1 = { 27, 94, 1, 1, "ENET_TXD1", "N/A", "N/A", "PB1", 0, 1, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_PB2 = { 28, 93, 1, 4, "ENET_TX_EN", "N/A", "N/A", "PB2", 0, 1, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_PB3 = { 29, 92, 1, 8, "ENET_CRS", "N/A", "N/A", "PB3", 0, 1, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_PB4 = { 30, 91, 1, 9, "ENET_RXD0", "N/A", "N/A", "PB4", 0, 1, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_PB5 = { 31, 90, 1, 10, "ENET_RXD1", "N/A", "N/A", "PB5", 0, 1, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_S10_SW_ENABLE = { 32, 89, 1, 14, "ENET_RX_ER", "N/A", "N/A", "S10_SW_ENABLE", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_AUX2 = { 33, 87, 1, 16, "ENET_MDC", "N/A", "N/A", "AUX2", 0, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_AUX1 = { 34, 86, 1, 17, "ENET_MDIO", "N/A", "N/A", "AUX1", 0, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_USP_UP_LED = { 35, 32, 1, 18, "USP_UP_LED", "PWM1.1", "CAP1.0", "USP_UP_LED", 0, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_CHAN_SEL = { 36, 33, 1, 19, "USB_TX_E1", "USB_PPWR1", "CAP1.1", "CHAN_SEL", 0, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_SHUNT_CH1 = { 37, 34, 1, 20, "USB_TX_DP1", "PWM1.2", "SCK0", "SHUNT_CH1", 0, 0, 0, 0, 0, 0 };
const ZEBRA_PINDEF ZEBRA_SHUNT_CH2 = { 38, 35, 1, 21, "USB_TX_DM1", "PWM1.3", "SSEL0", "SHUNT_CH2", 0, 0, 0, 0, 1, 0 };
const ZEBRA_PINDEF ZEBRA_PWM_GCA1 = { 39, 37, 1, 23, "USB_RX_DP1", "PWM1.4", "MISO0", "PWM_GCA1", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_PWM_GCA2 = { 40, 38, 1, 24, "USB_RX_DM1", "PWM1.5", "MOSI0", "PWM_GCA2", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_MCU_VBUS = { 41, 21, 1, 30, "N/A", "VBUS", "AD0.4", "MCU_VBUS", 0, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_PIC_ERR = { 42, 20, 1, 31, "N/A", "SCK1", "AD0.5", "PIC_ERR", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE0 = { 43, 75, 2, 0, "PWM1.1", "TXD1", "TRACECLK", "TRACE0", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE1 = { 44, 74, 2, 1, "PWM1.2", "RXD1", "PIPESTAT0", "TRACE1", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE2 = { 45, 73, 2, 2, "PWM1.3", "CTS1", "PIPESTAT1", "TRACE2", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE3 = { 46, 70, 2, 3, "PWM1.4", "DCD1", "PIPESTAT2", "TRACE3", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE4 = { 47, 69, 2, 4, "PWM1.5", "DSR1", "TRACESYNC", "TRACE4", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE5 = { 48, 68, 2, 5, "PWM1.6", "DTR1", "TRACEPKT0", "TRACE5", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE6 = { 49, 67, 2, 6, "PCAP1.0", "RI1", "TRACEPKT1", "TRACE6", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE7 = { 50, 66, 2, 7, "RD2", "RTS1", "TRACEPKT2", "TRACE7", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_TRACE8 = { 51, 65, 2, 8, "TD2", "TXD2", "TRACEPKT3", "TRACE8", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_USB_CONNECT = { 52, 64, 2, 9, "USB_CONNECT", "RXD2", "EXTIN0", "USB_CONNECT", 0, 255, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_L14_BOOT_CONTROL = { 53, 53, 2, 10, "EINT0", "N/A", "N/A", "L14_BOOT_CONTROL", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_INT2_RX = { 54, 52, 2, 11, "EINT1", "MCIDAT1", "I2STX_CLK", "INT2_RX", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_INT_TX = { 55, 51, 2, 12, "EINT2", "MCIDAT2", "I2STX_WS", "INT_TX", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_INT_RX = { 56, 50, 2, 13, "EINT3", "MCIDAT3", "I2STX_SDA", "INT_RX", 0, 1, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_MATCH2P0 = { 57, 82, 4, 28, "N/A", "MAT2.0", "TXD3", "MATCH2P0", 2, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF ZEBRA_MATCH2P1 = { 58, 85, 4, 29, "N/A", "MAT2.1", "RXD3", "MATCH2P1", 2, 0, 0, 0, 0, 1 };
const ZEBRA_PINDEF* ZEBRA_PINS[NUM_PINDEFS] = {
    &ZEBRA_PIC_TXD, &ZEBRA_PIC_RXD, &ZEBRA_TXD1, &ZEBRA_RXD1, &ZEBRA_IR_SIG, &ZEBRA_ST_LED2, 
    &ZEBRA_ST_LED3, &ZEBRA_ST_LED4, &ZEBRA_ST_LED5, &ZEBRA_ST_LED6, &ZEBRA_SDA2, &ZEBRA_SCL2, 
    &ZEBRA_SPI_CLK, &ZEBRA_SPI_CSEL, &ZEBRA_SPI_MISO, &ZEBRA_SPI_MOSI, &ZEBRA_SPI_HOLD, 
    &ZEBRA_MCU_RESET_OUT, &ZEBRA_GLOBAL_RESET, &ZEBRA_PIC_RESET, &ZEBRA_MCU_3V3_EN, &ZEBRA_MCU_1V8_EN, 
    &ZEBRA_SDA, &ZEBRA_SCL, &ZEBRA_USB_DP, &ZEBRA_USB_DM, &ZEBRA_PB0, &ZEBRA_PB1, &ZEBRA_PB2, 
    &ZEBRA_PB3, &ZEBRA_PB4, &ZEBRA_PB5, &ZEBRA_S10_SW_ENABLE, &ZEBRA_AUX2, &ZEBRA_AUX1, 
    &ZEBRA_USP_UP_LED, &ZEBRA_CHAN_SEL, &ZEBRA_SHUNT_CH1, &ZEBRA_SHUNT_CH2, &ZEBRA_PWM_GCA1, 
    &ZEBRA_PWM_GCA2, &ZEBRA_MCU_VBUS, &ZEBRA_PIC_ERR, &ZEBRA_TRACE0, &ZEBRA_TRACE1, &ZEBRA_TRACE2, 
    &ZEBRA_TRACE3, &ZEBRA_TRACE4, &ZEBRA_TRACE5, &ZEBRA_TRACE6, &ZEBRA_TRACE7, &ZEBRA_TRACE8, 
    &ZEBRA_USB_CONNECT, &ZEBRA_L14_BOOT_CONTROL, &ZEBRA_INT2_RX, &ZEBRA_INT_TX, &ZEBRA_INT_RX, 
    &ZEBRA_MATCH2P0, &ZEBRA_MATCH2P1, 
};
