//************************************************************************
//************************************************************************
//***
//***  NOTE:  This file was automatically generated by MKPINS
//***  Processing Date/Time:     Mon 24-Jun-2019 13:48:40
//***  Input Pin Info CSV file:  pinout.csv
//***  Project Name Prefix:      ZEBRA
//***  Output C-File:            zebra_gpio.c
//***  Output H-File:            zebra_gpio.h
//***
//************************************************************************
//************************************************************************

typedef struct tagZEBRA_PINDEF {
  int seq;
  int pinnum;
  int port;
  int bit;
  char *altfunc1;
  char *altfunc2;
  char *altfunc3;
  char *signame;
  int func;
  int inout;
  int mode;
  int odrain;
  int def;
  int active;
} ZEBRA_PINDEF;

extern const ZEBRA_PINDEF ZEBRA_PIC_TXD;
extern const ZEBRA_PINDEF ZEBRA_PIC_RXD;
extern const ZEBRA_PINDEF ZEBRA_TXD1;
extern const ZEBRA_PINDEF ZEBRA_RXD1;
extern const ZEBRA_PINDEF ZEBRA_IR_SIG;
extern const ZEBRA_PINDEF ZEBRA_ST_LED2;
extern const ZEBRA_PINDEF ZEBRA_ST_LED3;
extern const ZEBRA_PINDEF ZEBRA_ST_LED4;
extern const ZEBRA_PINDEF ZEBRA_ST_LED5;
extern const ZEBRA_PINDEF ZEBRA_ST_LED6;
extern const ZEBRA_PINDEF ZEBRA_SDA2;
extern const ZEBRA_PINDEF ZEBRA_SCL2;
extern const ZEBRA_PINDEF ZEBRA_SPI_CLK;
extern const ZEBRA_PINDEF ZEBRA_SPI_CSEL;
extern const ZEBRA_PINDEF ZEBRA_SPI_MISO;
extern const ZEBRA_PINDEF ZEBRA_SPI_MOSI;
extern const ZEBRA_PINDEF ZEBRA_SPI_HOLD;
extern const ZEBRA_PINDEF ZEBRA_MCU_RESET_OUT;
extern const ZEBRA_PINDEF ZEBRA_GLOBAL_RESET;
extern const ZEBRA_PINDEF ZEBRA_PIC_RESET;
extern const ZEBRA_PINDEF ZEBRA_MCU_3V3_EN;
extern const ZEBRA_PINDEF ZEBRA_MCU_1V8_EN;
extern const ZEBRA_PINDEF ZEBRA_SDA;
extern const ZEBRA_PINDEF ZEBRA_SCL;
extern const ZEBRA_PINDEF ZEBRA_USB_DP;
extern const ZEBRA_PINDEF ZEBRA_USB_DM;
extern const ZEBRA_PINDEF ZEBRA_PB0;
extern const ZEBRA_PINDEF ZEBRA_PB1;
extern const ZEBRA_PINDEF ZEBRA_PB2;
extern const ZEBRA_PINDEF ZEBRA_PB3;
extern const ZEBRA_PINDEF ZEBRA_PB4;
extern const ZEBRA_PINDEF ZEBRA_PB5;
extern const ZEBRA_PINDEF ZEBRA_S10_SW_ENABLE;
extern const ZEBRA_PINDEF ZEBRA_AUX2;
extern const ZEBRA_PINDEF ZEBRA_AUX1;
extern const ZEBRA_PINDEF ZEBRA_USP_UP_LED;
extern const ZEBRA_PINDEF ZEBRA_CHAN_SEL;
extern const ZEBRA_PINDEF ZEBRA_SHUNT_CH1;
extern const ZEBRA_PINDEF ZEBRA_SHUNT_CH2;
extern const ZEBRA_PINDEF ZEBRA_PWM_GCA1;
extern const ZEBRA_PINDEF ZEBRA_PWM_GCA2;
extern const ZEBRA_PINDEF ZEBRA_MCU_VBUS;
extern const ZEBRA_PINDEF ZEBRA_PIC_ERR;
extern const ZEBRA_PINDEF ZEBRA_TRACE0;
extern const ZEBRA_PINDEF ZEBRA_TRACE1;
extern const ZEBRA_PINDEF ZEBRA_TRACE2;
extern const ZEBRA_PINDEF ZEBRA_TRACE3;
extern const ZEBRA_PINDEF ZEBRA_TRACE4;
extern const ZEBRA_PINDEF ZEBRA_TRACE5;
extern const ZEBRA_PINDEF ZEBRA_TRACE6;
extern const ZEBRA_PINDEF ZEBRA_TRACE7;
extern const ZEBRA_PINDEF ZEBRA_TRACE8;
extern const ZEBRA_PINDEF ZEBRA_USB_CONNECT;
extern const ZEBRA_PINDEF ZEBRA_L14_BOOT_CONTROL;
extern const ZEBRA_PINDEF ZEBRA_INT2_RX;
extern const ZEBRA_PINDEF ZEBRA_INT_TX;
extern const ZEBRA_PINDEF ZEBRA_INT_RX;
extern const ZEBRA_PINDEF ZEBRA_MATCH2P0;
extern const ZEBRA_PINDEF ZEBRA_MATCH2P1;
#define NUM_PINDEFS (59)
extern const ZEBRA_PINDEF* ZEBRA_PINS[NUM_PINDEFS];

#define ZEBRA_PINSEL0_INIT (0xffffffffc0a00055)
#define ZEBRA_PINSEL1_INIT (0x01400fff)
#define ZEBRA_PINSEL2_INIT (0x00000000)
#define ZEBRA_PINSEL3_INIT (0x00000000)
#define ZEBRA_PINSEL4_INIT (0x00000000)
#define ZEBRA_PINSEL5_INIT (0x00000000)
#define ZEBRA_PINSEL6_INIT (0x00000000)
#define ZEBRA_PINSEL7_INIT (0x00000000)
#define ZEBRA_PINSEL8_INIT (0x00000000)
#define ZEBRA_PINSEL9_INIT (0x0a000000)
#define ZEBRA_PINSEL10_INIT (0x00000000)

#define ZEBRA_PINMODE0_INIT (0x00000000)
#define ZEBRA_PINMODE1_INIT (0x00000000)
#define ZEBRA_PINMODE2_INIT (0x00000000)
#define ZEBRA_PINMODE3_INIT (0x00000000)
#define ZEBRA_PINMODE4_INIT (0x00000000)
#define ZEBRA_PINMODE5_INIT (0x00000000)
#define ZEBRA_PINMODE6_INIT (0x00000000)
#define ZEBRA_PINMODE7_INIT (0x00000000)
#define ZEBRA_PINMODE8_INIT (0x00000000)
#define ZEBRA_PINMODE9_INIT (0x00000000)

#define ZEBRA_PINMODE_OD0_INIT (0x00400000)
#define ZEBRA_PINMODE_OD1_INIT (0x00000000)
#define ZEBRA_PINMODE_OD2_INIT (0x00000000)
#define ZEBRA_PINMODE_OD3_INIT (0x00000000)
#define ZEBRA_PINMODE_OD4_INIT (0x00000000)

#define ZEBRA_FIODIR0_INIT (0x01800fe6)
#define ZEBRA_FIODIR1_INIT (0x003f0000)
#define ZEBRA_FIODIR2_INIT (0x00000000)
#define ZEBRA_FIODIR3_INIT (0x00000000)
#define ZEBRA_FIODIR4_INIT (0x30000000)

#define ZEBRA_FIOPIN0_INIT (0x00400000)
#define ZEBRA_FIOPIN1_INIT (0x00200000)
#define ZEBRA_FIOPIN2_INIT (0x00000000)
#define ZEBRA_FIOPIN3_INIT (0x00000000)
#define ZEBRA_FIOPIN4_INIT (0x00000000)

#define ZEBRA_FIOMASK0_INIT (0x9e3ffc0f)
#define ZEBRA_FIOMASK1_INIT (0x3e40b8ec)
#define ZEBRA_FIOMASK2_INIT (0xffffc000)
#define ZEBRA_FIOMASK3_INIT (0xffffffff)
#define ZEBRA_FIOMASK4_INIT (0xffffffff)

#define ZEBRA_PIC_TXD_PORT                  (0)
#define ZEBRA_PIC_TXD_BIT                   (0)
#define ZEBRA_PIC_RXD_PORT                  (0)
#define ZEBRA_PIC_RXD_BIT                   (1)
#define ZEBRA_TXD1_PORT                     (0)
#define ZEBRA_TXD1_BIT                      (2)
#define ZEBRA_RXD1_PORT                     (0)
#define ZEBRA_RXD1_BIT                      (3)
#define ZEBRA_IR_SIG_PORT                   (0)
#define ZEBRA_IR_SIG_BIT                    (4)
#define ZEBRA_ST_LED2_PORT                  (0)
#define ZEBRA_ST_LED2_BIT                   (5)
#define ZEBRA_ST_LED3_PORT                  (0)
#define ZEBRA_ST_LED3_BIT                   (6)
#define ZEBRA_ST_LED4_PORT                  (0)
#define ZEBRA_ST_LED4_BIT                   (7)
#define ZEBRA_ST_LED5_PORT                  (0)
#define ZEBRA_ST_LED5_BIT                   (8)
#define ZEBRA_ST_LED6_PORT                  (0)
#define ZEBRA_ST_LED6_BIT                   (9)
#define ZEBRA_SDA2_PORT                     (0)
#define ZEBRA_SDA2_BIT                      (10)
#define ZEBRA_SCL2_PORT                     (0)
#define ZEBRA_SCL2_BIT                      (11)
#define ZEBRA_SPI_CLK_PORT                  (0)
#define ZEBRA_SPI_CLK_BIT                   (15)
#define ZEBRA_SPI_CSEL_PORT                 (0)
#define ZEBRA_SPI_CSEL_BIT                  (16)
#define ZEBRA_SPI_MISO_PORT                 (0)
#define ZEBRA_SPI_MISO_BIT                  (17)
#define ZEBRA_SPI_MOSI_PORT                 (0)
#define ZEBRA_SPI_MOSI_BIT                  (18)
#define ZEBRA_SPI_HOLD_PORT                 (0)
#define ZEBRA_SPI_HOLD_BIT                  (19)
#define ZEBRA_MCU_RESET_OUT_PORT            (0)
#define ZEBRA_MCU_RESET_OUT_BIT             (20)
#define ZEBRA_GLOBAL_RESET_PORT             (0)
#define ZEBRA_GLOBAL_RESET_BIT              (21)
#define ZEBRA_PIC_RESET_PORT                (0)
#define ZEBRA_PIC_RESET_BIT                 (22)
#define ZEBRA_MCU_3V3_EN_PORT               (0)
#define ZEBRA_MCU_3V3_EN_BIT                (23)
#define ZEBRA_MCU_1V8_EN_PORT               (0)
#define ZEBRA_MCU_1V8_EN_BIT                (24)
#define ZEBRA_SDA_PORT                      (0)
#define ZEBRA_SDA_BIT                       (27)
#define ZEBRA_SCL_PORT                      (0)
#define ZEBRA_SCL_BIT                       (28)
#define ZEBRA_USB_DP_PORT                   (0)
#define ZEBRA_USB_DP_BIT                    (29)
#define ZEBRA_USB_DM_PORT                   (0)
#define ZEBRA_USB_DM_BIT                    (30)
#define ZEBRA_PB0_PORT                      (1)
#define ZEBRA_PB0_BIT                       (0)
#define ZEBRA_PB1_PORT                      (1)
#define ZEBRA_PB1_BIT                       (1)
#define ZEBRA_PB2_PORT                      (1)
#define ZEBRA_PB2_BIT                       (4)
#define ZEBRA_PB3_PORT                      (1)
#define ZEBRA_PB3_BIT                       (8)
#define ZEBRA_PB4_PORT                      (1)
#define ZEBRA_PB4_BIT                       (9)
#define ZEBRA_PB5_PORT                      (1)
#define ZEBRA_PB5_BIT                       (10)
#define ZEBRA_S10_SW_ENABLE_PORT            (1)
#define ZEBRA_S10_SW_ENABLE_BIT             (14)
#define ZEBRA_AUX2_PORT                     (1)
#define ZEBRA_AUX2_BIT                      (16)
#define ZEBRA_AUX1_PORT                     (1)
#define ZEBRA_AUX1_BIT                      (17)
#define ZEBRA_USP_UP_LED_PORT               (1)
#define ZEBRA_USP_UP_LED_BIT                (18)
#define ZEBRA_CHAN_SEL_PORT                 (1)
#define ZEBRA_CHAN_SEL_BIT                  (19)
#define ZEBRA_SHUNT_CH1_PORT                (1)
#define ZEBRA_SHUNT_CH1_BIT                 (20)
#define ZEBRA_SHUNT_CH2_PORT                (1)
#define ZEBRA_SHUNT_CH2_BIT                 (21)
#define ZEBRA_PWM_GCA1_PORT                 (1)
#define ZEBRA_PWM_GCA1_BIT                  (23)
#define ZEBRA_PWM_GCA2_PORT                 (1)
#define ZEBRA_PWM_GCA2_BIT                  (24)
#define ZEBRA_MCU_VBUS_PORT                 (1)
#define ZEBRA_MCU_VBUS_BIT                  (30)
#define ZEBRA_PIC_ERR_PORT                  (1)
#define ZEBRA_PIC_ERR_BIT                   (31)
#define ZEBRA_TRACE0_PORT                   (2)
#define ZEBRA_TRACE0_BIT                    (0)
#define ZEBRA_TRACE1_PORT                   (2)
#define ZEBRA_TRACE1_BIT                    (1)
#define ZEBRA_TRACE2_PORT                   (2)
#define ZEBRA_TRACE2_BIT                    (2)
#define ZEBRA_TRACE3_PORT                   (2)
#define ZEBRA_TRACE3_BIT                    (3)
#define ZEBRA_TRACE4_PORT                   (2)
#define ZEBRA_TRACE4_BIT                    (4)
#define ZEBRA_TRACE5_PORT                   (2)
#define ZEBRA_TRACE5_BIT                    (5)
#define ZEBRA_TRACE6_PORT                   (2)
#define ZEBRA_TRACE6_BIT                    (6)
#define ZEBRA_TRACE7_PORT                   (2)
#define ZEBRA_TRACE7_BIT                    (7)
#define ZEBRA_TRACE8_PORT                   (2)
#define ZEBRA_TRACE8_BIT                    (8)
#define ZEBRA_USB_CONNECT_PORT              (2)
#define ZEBRA_USB_CONNECT_BIT               (9)
#define ZEBRA_L14_BOOT_CONTROL_PORT         (2)
#define ZEBRA_L14_BOOT_CONTROL_BIT          (10)
#define ZEBRA_INT2_RX_PORT                  (2)
#define ZEBRA_INT2_RX_BIT                   (11)
#define ZEBRA_INT_TX_PORT                   (2)
#define ZEBRA_INT_TX_BIT                    (12)
#define ZEBRA_INT_RX_PORT                   (2)
#define ZEBRA_INT_RX_BIT                    (13)
#define ZEBRA_MATCH2P0_PORT                 (4)
#define ZEBRA_MATCH2P0_BIT                  (28)
#define ZEBRA_MATCH2P1_PORT                 (4)
#define ZEBRA_MATCH2P1_BIT                  (29)

#define ZEBRA_GET_PIC_TXD                     ((LPC_GPIO0->FIOPIN & (1<<0)) >> 0)
#define ZEBRA_SET_PIC_TXD                      (LPC_GPIO0->FIOSET = (1<<0))
#define ZEBRA_CLR_PIC_TXD                      (LPC_GPIO0->FIOCLR = (1<<0))
#define ZEBRA_ON_PIC_TXD                      (LPC_GPIO0->FIOSET = (1<<0))
#define ZEBRA_OFF_PIC_TXD                      (LPC_GPIO0->FIOCLR = (1<<0))
#define ZEBRA_QON_PIC_TXD                     ((LPC_GPIO0->FIOPIN & (1<<0)) >> 0)
#define ZEBRA_GET_PIC_RXD                     ((LPC_GPIO0->FIOPIN & (1<<1)) >> 1)
#define ZEBRA_SET_PIC_RXD                      (LPC_GPIO0->FIOSET = (1<<1))
#define ZEBRA_CLR_PIC_RXD                      (LPC_GPIO0->FIOCLR = (1<<1))
#define ZEBRA_ON_PIC_RXD                      (LPC_GPIO0->FIOSET = (1<<1))
#define ZEBRA_OFF_PIC_RXD                      (LPC_GPIO0->FIOCLR = (1<<1))
#define ZEBRA_QON_PIC_RXD                     ((LPC_GPIO0->FIOPIN & (1<<1)) >> 1)
#define ZEBRA_GET_TXD1                        ((LPC_GPIO0->FIOPIN & (1<<2)) >> 2)
#define ZEBRA_SET_TXD1                         (LPC_GPIO0->FIOSET = (1<<2))
#define ZEBRA_CLR_TXD1                         (LPC_GPIO0->FIOCLR = (1<<2))
#define ZEBRA_ON_TXD1                         (LPC_GPIO0->FIOSET = (1<<2))
#define ZEBRA_OFF_TXD1                         (LPC_GPIO0->FIOCLR = (1<<2))
#define ZEBRA_QON_TXD1                        ((LPC_GPIO0->FIOPIN & (1<<2)) >> 2)
#define ZEBRA_GET_RXD1                        ((LPC_GPIO0->FIOPIN & (1<<3)) >> 3)
#define ZEBRA_SET_RXD1                         (LPC_GPIO0->FIOSET = (1<<3))
#define ZEBRA_CLR_RXD1                         (LPC_GPIO0->FIOCLR = (1<<3))
#define ZEBRA_ON_RXD1                         (LPC_GPIO0->FIOSET = (1<<3))
#define ZEBRA_OFF_RXD1                         (LPC_GPIO0->FIOCLR = (1<<3))
#define ZEBRA_QON_RXD1                        ((LPC_GPIO0->FIOPIN & (1<<3)) >> 3)
#define ZEBRA_GET_IR_SIG                      ((LPC_GPIO0->FIOPIN & (1<<4)) >> 4)
#define ZEBRA_SET_IR_SIG                       (LPC_GPIO0->FIOSET = (1<<4))
#define ZEBRA_CLR_IR_SIG                       (LPC_GPIO0->FIOCLR = (1<<4))
#define ZEBRA_ON_IR_SIG                       (LPC_GPIO0->FIOSET = (1<<4))
#define ZEBRA_OFF_IR_SIG                       (LPC_GPIO0->FIOCLR = (1<<4))
#define ZEBRA_QON_IR_SIG                      ((LPC_GPIO0->FIOPIN & (1<<4)) >> 4)
#define ZEBRA_GET_ST_LED2                     ((LPC_GPIO0->FIOPIN & (1<<5)) >> 5)
#define ZEBRA_SET_ST_LED2                      (LPC_GPIO0->FIOSET = (1<<5))
#define ZEBRA_CLR_ST_LED2                      (LPC_GPIO0->FIOCLR = (1<<5))
#define ZEBRA_ON_ST_LED2                      (LPC_GPIO0->FIOSET = (1<<5))
#define ZEBRA_OFF_ST_LED2                      (LPC_GPIO0->FIOCLR = (1<<5))
#define ZEBRA_QON_ST_LED2                     ((LPC_GPIO0->FIOPIN & (1<<5)) >> 5)
#define ZEBRA_GET_ST_LED3                     ((LPC_GPIO0->FIOPIN & (1<<6)) >> 6)
#define ZEBRA_SET_ST_LED3                      (LPC_GPIO0->FIOSET = (1<<6))
#define ZEBRA_CLR_ST_LED3                      (LPC_GPIO0->FIOCLR = (1<<6))
#define ZEBRA_ON_ST_LED3                       (LPC_GPIO0->FIOCLR = (1<<6))
#define ZEBRA_OFF_ST_LED3                      (LPC_GPIO0->FIOSET = (1<<6))
#define ZEBRA_QON_ST_LED3                    (((LPC_GPIO0->FIOPIN & (1<<6)) >> 6)^1)
#define ZEBRA_GET_ST_LED4                     ((LPC_GPIO0->FIOPIN & (1<<7)) >> 7)
#define ZEBRA_SET_ST_LED4                      (LPC_GPIO0->FIOSET = (1<<7))
#define ZEBRA_CLR_ST_LED4                      (LPC_GPIO0->FIOCLR = (1<<7))
#define ZEBRA_ON_ST_LED4                       (LPC_GPIO0->FIOCLR = (1<<7))
#define ZEBRA_OFF_ST_LED4                      (LPC_GPIO0->FIOSET = (1<<7))
#define ZEBRA_QON_ST_LED4                    (((LPC_GPIO0->FIOPIN & (1<<7)) >> 7)^1)
#define ZEBRA_GET_ST_LED5                     ((LPC_GPIO0->FIOPIN & (1<<8)) >> 8)
#define ZEBRA_SET_ST_LED5                      (LPC_GPIO0->FIOSET = (1<<8))
#define ZEBRA_CLR_ST_LED5                      (LPC_GPIO0->FIOCLR = (1<<8))
#define ZEBRA_ON_ST_LED5                       (LPC_GPIO0->FIOCLR = (1<<8))
#define ZEBRA_OFF_ST_LED5                      (LPC_GPIO0->FIOSET = (1<<8))
#define ZEBRA_QON_ST_LED5                    (((LPC_GPIO0->FIOPIN & (1<<8)) >> 8)^1)
#define ZEBRA_GET_ST_LED6                     ((LPC_GPIO0->FIOPIN & (1<<9)) >> 9)
#define ZEBRA_SET_ST_LED6                      (LPC_GPIO0->FIOSET = (1<<9))
#define ZEBRA_CLR_ST_LED6                      (LPC_GPIO0->FIOCLR = (1<<9))
#define ZEBRA_ON_ST_LED6                       (LPC_GPIO0->FIOCLR = (1<<9))
#define ZEBRA_OFF_ST_LED6                      (LPC_GPIO0->FIOSET = (1<<9))
#define ZEBRA_QON_ST_LED6                    (((LPC_GPIO0->FIOPIN & (1<<9)) >> 9)^1)
#define ZEBRA_GET_SDA2                        ((LPC_GPIO0->FIOPIN & (1<<10)) >> 10)
#define ZEBRA_SET_SDA2                         (LPC_GPIO0->FIOSET = (1<<10))
#define ZEBRA_CLR_SDA2                         (LPC_GPIO0->FIOCLR = (1<<10))
#define ZEBRA_ON_SDA2                         (LPC_GPIO0->FIOSET = (1<<10))
#define ZEBRA_OFF_SDA2                         (LPC_GPIO0->FIOCLR = (1<<10))
#define ZEBRA_QON_SDA2                        ((LPC_GPIO0->FIOPIN & (1<<10)) >> 10)
#define ZEBRA_GET_SCL2                        ((LPC_GPIO0->FIOPIN & (1<<11)) >> 11)
#define ZEBRA_SET_SCL2                         (LPC_GPIO0->FIOSET = (1<<11))
#define ZEBRA_CLR_SCL2                         (LPC_GPIO0->FIOCLR = (1<<11))
#define ZEBRA_ON_SCL2                         (LPC_GPIO0->FIOSET = (1<<11))
#define ZEBRA_OFF_SCL2                         (LPC_GPIO0->FIOCLR = (1<<11))
#define ZEBRA_QON_SCL2                        ((LPC_GPIO0->FIOPIN & (1<<11)) >> 11)
#define ZEBRA_GET_SPI_CLK                     ((LPC_GPIO0->FIOPIN & (1<<15)) >> 15)
#define ZEBRA_SET_SPI_CLK                      (LPC_GPIO0->FIOSET = (1<<15))
#define ZEBRA_CLR_SPI_CLK                      (LPC_GPIO0->FIOCLR = (1<<15))
#define ZEBRA_ON_SPI_CLK                      (LPC_GPIO0->FIOSET = (1<<15))
#define ZEBRA_OFF_SPI_CLK                      (LPC_GPIO0->FIOCLR = (1<<15))
#define ZEBRA_QON_SPI_CLK                     ((LPC_GPIO0->FIOPIN & (1<<15)) >> 15)
#define ZEBRA_GET_SPI_CSEL                    ((LPC_GPIO0->FIOPIN & (1<<16)) >> 16)
#define ZEBRA_SET_SPI_CSEL                     (LPC_GPIO0->FIOSET = (1<<16))
#define ZEBRA_CLR_SPI_CSEL                     (LPC_GPIO0->FIOCLR = (1<<16))
#define ZEBRA_ON_SPI_CSEL                     (LPC_GPIO0->FIOSET = (1<<16))
#define ZEBRA_OFF_SPI_CSEL                     (LPC_GPIO0->FIOCLR = (1<<16))
#define ZEBRA_QON_SPI_CSEL                    ((LPC_GPIO0->FIOPIN & (1<<16)) >> 16)
#define ZEBRA_GET_SPI_MISO                    ((LPC_GPIO0->FIOPIN & (1<<17)) >> 17)
#define ZEBRA_SET_SPI_MISO                     (LPC_GPIO0->FIOSET = (1<<17))
#define ZEBRA_CLR_SPI_MISO                     (LPC_GPIO0->FIOCLR = (1<<17))
#define ZEBRA_ON_SPI_MISO                     (LPC_GPIO0->FIOSET = (1<<17))
#define ZEBRA_OFF_SPI_MISO                     (LPC_GPIO0->FIOCLR = (1<<17))
#define ZEBRA_QON_SPI_MISO                    ((LPC_GPIO0->FIOPIN & (1<<17)) >> 17)
#define ZEBRA_GET_SPI_MOSI                    ((LPC_GPIO0->FIOPIN & (1<<18)) >> 18)
#define ZEBRA_SET_SPI_MOSI                     (LPC_GPIO0->FIOSET = (1<<18))
#define ZEBRA_CLR_SPI_MOSI                     (LPC_GPIO0->FIOCLR = (1<<18))
#define ZEBRA_ON_SPI_MOSI                     (LPC_GPIO0->FIOSET = (1<<18))
#define ZEBRA_OFF_SPI_MOSI                     (LPC_GPIO0->FIOCLR = (1<<18))
#define ZEBRA_QON_SPI_MOSI                    ((LPC_GPIO0->FIOPIN & (1<<18)) >> 18)
#define ZEBRA_GET_SPI_HOLD                    ((LPC_GPIO0->FIOPIN & (1<<19)) >> 19)
#define ZEBRA_SET_SPI_HOLD                     (LPC_GPIO0->FIOSET = (1<<19))
#define ZEBRA_CLR_SPI_HOLD                     (LPC_GPIO0->FIOCLR = (1<<19))
#define ZEBRA_ON_SPI_HOLD                     (LPC_GPIO0->FIOSET = (1<<19))
#define ZEBRA_OFF_SPI_HOLD                     (LPC_GPIO0->FIOCLR = (1<<19))
#define ZEBRA_QON_SPI_HOLD                    ((LPC_GPIO0->FIOPIN & (1<<19)) >> 19)
#define ZEBRA_GET_MCU_RESET_OUT               ((LPC_GPIO0->FIOPIN & (1<<20)) >> 20)
#define ZEBRA_SET_MCU_RESET_OUT                (LPC_GPIO0->FIOSET = (1<<20))
#define ZEBRA_CLR_MCU_RESET_OUT                (LPC_GPIO0->FIOCLR = (1<<20))
#define ZEBRA_ON_MCU_RESET_OUT                (LPC_GPIO0->FIOSET = (1<<20))
#define ZEBRA_OFF_MCU_RESET_OUT                (LPC_GPIO0->FIOCLR = (1<<20))
#define ZEBRA_QON_MCU_RESET_OUT               ((LPC_GPIO0->FIOPIN & (1<<20)) >> 20)
#define ZEBRA_GET_GLOBAL_RESET                ((LPC_GPIO0->FIOPIN & (1<<21)) >> 21)
#define ZEBRA_SET_GLOBAL_RESET                 (LPC_GPIO0->FIOSET = (1<<21))
#define ZEBRA_CLR_GLOBAL_RESET                 (LPC_GPIO0->FIOCLR = (1<<21))
#define ZEBRA_ON_GLOBAL_RESET                 (LPC_GPIO0->FIOSET = (1<<21))
#define ZEBRA_OFF_GLOBAL_RESET                 (LPC_GPIO0->FIOCLR = (1<<21))
#define ZEBRA_QON_GLOBAL_RESET                ((LPC_GPIO0->FIOPIN & (1<<21)) >> 21)
#define ZEBRA_GET_PIC_RESET                   ((LPC_GPIO0->FIOPIN & (1<<22)) >> 22)
#define ZEBRA_OPEN_PIC_RESET                    (LPC_GPIO0->FIOSET = (1<<22))
#define ZEBRA_SINK_PIC_RESET                    (LPC_GPIO0->FIOCLR = (1<<22))
#define ZEBRA_GET_MCU_3V3_EN                  ((LPC_GPIO0->FIOPIN & (1<<23)) >> 23)
#define ZEBRA_SET_MCU_3V3_EN                   (LPC_GPIO0->FIOSET = (1<<23))
#define ZEBRA_CLR_MCU_3V3_EN                   (LPC_GPIO0->FIOCLR = (1<<23))
#define ZEBRA_ON_MCU_3V3_EN                    (LPC_GPIO0->FIOCLR = (1<<23))
#define ZEBRA_OFF_MCU_3V3_EN                   (LPC_GPIO0->FIOSET = (1<<23))
#define ZEBRA_QON_MCU_3V3_EN                 (((LPC_GPIO0->FIOPIN & (1<<23)) >> 23)^1)
#define ZEBRA_GET_MCU_1V8_EN                  ((LPC_GPIO0->FIOPIN & (1<<24)) >> 24)
#define ZEBRA_SET_MCU_1V8_EN                   (LPC_GPIO0->FIOSET = (1<<24))
#define ZEBRA_CLR_MCU_1V8_EN                   (LPC_GPIO0->FIOCLR = (1<<24))
#define ZEBRA_ON_MCU_1V8_EN                    (LPC_GPIO0->FIOCLR = (1<<24))
#define ZEBRA_OFF_MCU_1V8_EN                   (LPC_GPIO0->FIOSET = (1<<24))
#define ZEBRA_QON_MCU_1V8_EN                 (((LPC_GPIO0->FIOPIN & (1<<24)) >> 24)^1)
#define ZEBRA_GET_SDA                         ((LPC_GPIO0->FIOPIN & (1<<27)) >> 27)
#define ZEBRA_SET_SDA                          (LPC_GPIO0->FIOSET = (1<<27))
#define ZEBRA_CLR_SDA                          (LPC_GPIO0->FIOCLR = (1<<27))
#define ZEBRA_ON_SDA                          (LPC_GPIO0->FIOSET = (1<<27))
#define ZEBRA_OFF_SDA                          (LPC_GPIO0->FIOCLR = (1<<27))
#define ZEBRA_QON_SDA                         ((LPC_GPIO0->FIOPIN & (1<<27)) >> 27)
#define ZEBRA_GET_SCL                         ((LPC_GPIO0->FIOPIN & (1<<28)) >> 28)
#define ZEBRA_SET_SCL                          (LPC_GPIO0->FIOSET = (1<<28))
#define ZEBRA_CLR_SCL                          (LPC_GPIO0->FIOCLR = (1<<28))
#define ZEBRA_ON_SCL                          (LPC_GPIO0->FIOSET = (1<<28))
#define ZEBRA_OFF_SCL                          (LPC_GPIO0->FIOCLR = (1<<28))
#define ZEBRA_QON_SCL                         ((LPC_GPIO0->FIOPIN & (1<<28)) >> 28)
#define ZEBRA_GET_USB_DP                      ((LPC_GPIO0->FIOPIN & (1<<29)) >> 29)
#define ZEBRA_SET_USB_DP                       (LPC_GPIO0->FIOSET = (1<<29))
#define ZEBRA_CLR_USB_DP                       (LPC_GPIO0->FIOCLR = (1<<29))
#define ZEBRA_ON_USB_DP                       (LPC_GPIO0->FIOSET = (1<<29))
#define ZEBRA_OFF_USB_DP                       (LPC_GPIO0->FIOCLR = (1<<29))
#define ZEBRA_QON_USB_DP                      ((LPC_GPIO0->FIOPIN & (1<<29)) >> 29)
#define ZEBRA_GET_USB_DM                      ((LPC_GPIO0->FIOPIN & (1<<30)) >> 30)
#define ZEBRA_SET_USB_DM                       (LPC_GPIO0->FIOSET = (1<<30))
#define ZEBRA_CLR_USB_DM                       (LPC_GPIO0->FIOCLR = (1<<30))
#define ZEBRA_ON_USB_DM                       (LPC_GPIO0->FIOSET = (1<<30))
#define ZEBRA_OFF_USB_DM                       (LPC_GPIO0->FIOCLR = (1<<30))
#define ZEBRA_QON_USB_DM                      ((LPC_GPIO0->FIOPIN & (1<<30)) >> 30)
#define ZEBRA_GET_PB0                         ((LPC_GPIO1->FIOPIN & (1<<0)) >> 0)
#define ZEBRA_SET_PB0                          (LPC_GPIO1->FIOSET = (1<<0))
#define ZEBRA_CLR_PB0                          (LPC_GPIO1->FIOCLR = (1<<0))
#define ZEBRA_ON_PB0                           (LPC_GPIO1->FIOCLR = (1<<0))
#define ZEBRA_OFF_PB0                          (LPC_GPIO1->FIOSET = (1<<0))
#define ZEBRA_QON_PB0                        (((LPC_GPIO1->FIOPIN & (1<<0)) >> 0)^1)
#define ZEBRA_GET_PB1                         ((LPC_GPIO1->FIOPIN & (1<<1)) >> 1)
#define ZEBRA_SET_PB1                          (LPC_GPIO1->FIOSET = (1<<1))
#define ZEBRA_CLR_PB1                          (LPC_GPIO1->FIOCLR = (1<<1))
#define ZEBRA_ON_PB1                           (LPC_GPIO1->FIOCLR = (1<<1))
#define ZEBRA_OFF_PB1                          (LPC_GPIO1->FIOSET = (1<<1))
#define ZEBRA_QON_PB1                        (((LPC_GPIO1->FIOPIN & (1<<1)) >> 1)^1)
#define ZEBRA_GET_PB2                         ((LPC_GPIO1->FIOPIN & (1<<4)) >> 4)
#define ZEBRA_SET_PB2                          (LPC_GPIO1->FIOSET = (1<<4))
#define ZEBRA_CLR_PB2                          (LPC_GPIO1->FIOCLR = (1<<4))
#define ZEBRA_ON_PB2                           (LPC_GPIO1->FIOCLR = (1<<4))
#define ZEBRA_OFF_PB2                          (LPC_GPIO1->FIOSET = (1<<4))
#define ZEBRA_QON_PB2                        (((LPC_GPIO1->FIOPIN & (1<<4)) >> 4)^1)
#define ZEBRA_GET_PB3                         ((LPC_GPIO1->FIOPIN & (1<<8)) >> 8)
#define ZEBRA_SET_PB3                          (LPC_GPIO1->FIOSET = (1<<8))
#define ZEBRA_CLR_PB3                          (LPC_GPIO1->FIOCLR = (1<<8))
#define ZEBRA_ON_PB3                           (LPC_GPIO1->FIOCLR = (1<<8))
#define ZEBRA_OFF_PB3                          (LPC_GPIO1->FIOSET = (1<<8))
#define ZEBRA_QON_PB3                        (((LPC_GPIO1->FIOPIN & (1<<8)) >> 8)^1)
#define ZEBRA_GET_PB4                         ((LPC_GPIO1->FIOPIN & (1<<9)) >> 9)
#define ZEBRA_SET_PB4                          (LPC_GPIO1->FIOSET = (1<<9))
#define ZEBRA_CLR_PB4                          (LPC_GPIO1->FIOCLR = (1<<9))
#define ZEBRA_ON_PB4                           (LPC_GPIO1->FIOCLR = (1<<9))
#define ZEBRA_OFF_PB4                          (LPC_GPIO1->FIOSET = (1<<9))
#define ZEBRA_QON_PB4                        (((LPC_GPIO1->FIOPIN & (1<<9)) >> 9)^1)
#define ZEBRA_GET_PB5                         ((LPC_GPIO1->FIOPIN & (1<<10)) >> 10)
#define ZEBRA_SET_PB5                          (LPC_GPIO1->FIOSET = (1<<10))
#define ZEBRA_CLR_PB5                          (LPC_GPIO1->FIOCLR = (1<<10))
#define ZEBRA_ON_PB5                           (LPC_GPIO1->FIOCLR = (1<<10))
#define ZEBRA_OFF_PB5                          (LPC_GPIO1->FIOSET = (1<<10))
#define ZEBRA_QON_PB5                        (((LPC_GPIO1->FIOPIN & (1<<10)) >> 10)^1)
#define ZEBRA_GET_S10_SW_ENABLE               ((LPC_GPIO1->FIOPIN & (1<<14)) >> 14)
#define ZEBRA_SET_S10_SW_ENABLE                (LPC_GPIO1->FIOSET = (1<<14))
#define ZEBRA_CLR_S10_SW_ENABLE                (LPC_GPIO1->FIOCLR = (1<<14))
#define ZEBRA_ON_S10_SW_ENABLE                (LPC_GPIO1->FIOSET = (1<<14))
#define ZEBRA_OFF_S10_SW_ENABLE                (LPC_GPIO1->FIOCLR = (1<<14))
#define ZEBRA_QON_S10_SW_ENABLE               ((LPC_GPIO1->FIOPIN & (1<<14)) >> 14)
#define ZEBRA_GET_AUX2                        ((LPC_GPIO1->FIOPIN & (1<<16)) >> 16)
#define ZEBRA_SET_AUX2                         (LPC_GPIO1->FIOSET = (1<<16))
#define ZEBRA_CLR_AUX2                         (LPC_GPIO1->FIOCLR = (1<<16))
#define ZEBRA_ON_AUX2                         (LPC_GPIO1->FIOSET = (1<<16))
#define ZEBRA_OFF_AUX2                         (LPC_GPIO1->FIOCLR = (1<<16))
#define ZEBRA_QON_AUX2                        ((LPC_GPIO1->FIOPIN & (1<<16)) >> 16)
#define ZEBRA_GET_AUX1                        ((LPC_GPIO1->FIOPIN & (1<<17)) >> 17)
#define ZEBRA_SET_AUX1                         (LPC_GPIO1->FIOSET = (1<<17))
#define ZEBRA_CLR_AUX1                         (LPC_GPIO1->FIOCLR = (1<<17))
#define ZEBRA_ON_AUX1                         (LPC_GPIO1->FIOSET = (1<<17))
#define ZEBRA_OFF_AUX1                         (LPC_GPIO1->FIOCLR = (1<<17))
#define ZEBRA_QON_AUX1                        ((LPC_GPIO1->FIOPIN & (1<<17)) >> 17)
#define ZEBRA_GET_USP_UP_LED                  ((LPC_GPIO1->FIOPIN & (1<<18)) >> 18)
#define ZEBRA_SET_USP_UP_LED                   (LPC_GPIO1->FIOSET = (1<<18))
#define ZEBRA_CLR_USP_UP_LED                   (LPC_GPIO1->FIOCLR = (1<<18))
#define ZEBRA_ON_USP_UP_LED                   (LPC_GPIO1->FIOSET = (1<<18))
#define ZEBRA_OFF_USP_UP_LED                   (LPC_GPIO1->FIOCLR = (1<<18))
#define ZEBRA_QON_USP_UP_LED                  ((LPC_GPIO1->FIOPIN & (1<<18)) >> 18)
#define ZEBRA_GET_CHAN_SEL                    ((LPC_GPIO1->FIOPIN & (1<<19)) >> 19)
#define ZEBRA_SET_CHAN_SEL                     (LPC_GPIO1->FIOSET = (1<<19))
#define ZEBRA_CLR_CHAN_SEL                     (LPC_GPIO1->FIOCLR = (1<<19))
#define ZEBRA_ON_CHAN_SEL                     (LPC_GPIO1->FIOSET = (1<<19))
#define ZEBRA_OFF_CHAN_SEL                     (LPC_GPIO1->FIOCLR = (1<<19))
#define ZEBRA_QON_CHAN_SEL                    ((LPC_GPIO1->FIOPIN & (1<<19)) >> 19)
#define ZEBRA_GET_SHUNT_CH1                   ((LPC_GPIO1->FIOPIN & (1<<20)) >> 20)
#define ZEBRA_SET_SHUNT_CH1                    (LPC_GPIO1->FIOSET = (1<<20))
#define ZEBRA_CLR_SHUNT_CH1                    (LPC_GPIO1->FIOCLR = (1<<20))
#define ZEBRA_ON_SHUNT_CH1                     (LPC_GPIO1->FIOCLR = (1<<20))
#define ZEBRA_OFF_SHUNT_CH1                    (LPC_GPIO1->FIOSET = (1<<20))
#define ZEBRA_QON_SHUNT_CH1                  (((LPC_GPIO1->FIOPIN & (1<<20)) >> 20)^1)
#define ZEBRA_GET_SHUNT_CH2                   ((LPC_GPIO1->FIOPIN & (1<<21)) >> 21)
#define ZEBRA_SET_SHUNT_CH2                    (LPC_GPIO1->FIOSET = (1<<21))
#define ZEBRA_CLR_SHUNT_CH2                    (LPC_GPIO1->FIOCLR = (1<<21))
#define ZEBRA_ON_SHUNT_CH2                     (LPC_GPIO1->FIOCLR = (1<<21))
#define ZEBRA_OFF_SHUNT_CH2                    (LPC_GPIO1->FIOSET = (1<<21))
#define ZEBRA_QON_SHUNT_CH2                  (((LPC_GPIO1->FIOPIN & (1<<21)) >> 21)^1)
#define ZEBRA_GET_PWM_GCA1                    ((LPC_GPIO1->FIOPIN & (1<<23)) >> 23)
#define ZEBRA_SET_PWM_GCA1                     (LPC_GPIO1->FIOSET = (1<<23))
#define ZEBRA_CLR_PWM_GCA1                     (LPC_GPIO1->FIOCLR = (1<<23))
#define ZEBRA_ON_PWM_GCA1                     (LPC_GPIO1->FIOSET = (1<<23))
#define ZEBRA_OFF_PWM_GCA1                     (LPC_GPIO1->FIOCLR = (1<<23))
#define ZEBRA_QON_PWM_GCA1                    ((LPC_GPIO1->FIOPIN & (1<<23)) >> 23)
#define ZEBRA_GET_PWM_GCA2                    ((LPC_GPIO1->FIOPIN & (1<<24)) >> 24)
#define ZEBRA_SET_PWM_GCA2                     (LPC_GPIO1->FIOSET = (1<<24))
#define ZEBRA_CLR_PWM_GCA2                     (LPC_GPIO1->FIOCLR = (1<<24))
#define ZEBRA_ON_PWM_GCA2                     (LPC_GPIO1->FIOSET = (1<<24))
#define ZEBRA_OFF_PWM_GCA2                     (LPC_GPIO1->FIOCLR = (1<<24))
#define ZEBRA_QON_PWM_GCA2                    ((LPC_GPIO1->FIOPIN & (1<<24)) >> 24)
#define ZEBRA_GET_MCU_VBUS                    ((LPC_GPIO1->FIOPIN & (1<<30)) >> 30)
#define ZEBRA_SET_MCU_VBUS                     (LPC_GPIO1->FIOSET = (1<<30))
#define ZEBRA_CLR_MCU_VBUS                     (LPC_GPIO1->FIOCLR = (1<<30))
#define ZEBRA_ON_MCU_VBUS                     (LPC_GPIO1->FIOSET = (1<<30))
#define ZEBRA_OFF_MCU_VBUS                     (LPC_GPIO1->FIOCLR = (1<<30))
#define ZEBRA_QON_MCU_VBUS                    ((LPC_GPIO1->FIOPIN & (1<<30)) >> 30)
#define ZEBRA_GET_PIC_ERR                     ((LPC_GPIO1->FIOPIN & (1<<31)) >> 31)
#define ZEBRA_SET_PIC_ERR                      (LPC_GPIO1->FIOSET = (1<<31))
#define ZEBRA_CLR_PIC_ERR                      (LPC_GPIO1->FIOCLR = (1<<31))
#define ZEBRA_ON_PIC_ERR                      (LPC_GPIO1->FIOSET = (1<<31))
#define ZEBRA_OFF_PIC_ERR                      (LPC_GPIO1->FIOCLR = (1<<31))
#define ZEBRA_QON_PIC_ERR                     ((LPC_GPIO1->FIOPIN & (1<<31)) >> 31)
#define ZEBRA_GET_TRACE0                      ((LPC_GPIO2->FIOPIN & (1<<0)) >> 0)
#define ZEBRA_SET_TRACE0                       (LPC_GPIO2->FIOSET = (1<<0))
#define ZEBRA_CLR_TRACE0                       (LPC_GPIO2->FIOCLR = (1<<0))
#define ZEBRA_ON_TRACE0                       (LPC_GPIO2->FIOSET = (1<<0))
#define ZEBRA_OFF_TRACE0                       (LPC_GPIO2->FIOCLR = (1<<0))
#define ZEBRA_QON_TRACE0                      ((LPC_GPIO2->FIOPIN & (1<<0)) >> 0)
#define ZEBRA_GET_TRACE1                      ((LPC_GPIO2->FIOPIN & (1<<1)) >> 1)
#define ZEBRA_SET_TRACE1                       (LPC_GPIO2->FIOSET = (1<<1))
#define ZEBRA_CLR_TRACE1                       (LPC_GPIO2->FIOCLR = (1<<1))
#define ZEBRA_ON_TRACE1                       (LPC_GPIO2->FIOSET = (1<<1))
#define ZEBRA_OFF_TRACE1                       (LPC_GPIO2->FIOCLR = (1<<1))
#define ZEBRA_QON_TRACE1                      ((LPC_GPIO2->FIOPIN & (1<<1)) >> 1)
#define ZEBRA_GET_TRACE2                      ((LPC_GPIO2->FIOPIN & (1<<2)) >> 2)
#define ZEBRA_SET_TRACE2                       (LPC_GPIO2->FIOSET = (1<<2))
#define ZEBRA_CLR_TRACE2                       (LPC_GPIO2->FIOCLR = (1<<2))
#define ZEBRA_ON_TRACE2                       (LPC_GPIO2->FIOSET = (1<<2))
#define ZEBRA_OFF_TRACE2                       (LPC_GPIO2->FIOCLR = (1<<2))
#define ZEBRA_QON_TRACE2                      ((LPC_GPIO2->FIOPIN & (1<<2)) >> 2)
#define ZEBRA_GET_TRACE3                      ((LPC_GPIO2->FIOPIN & (1<<3)) >> 3)
#define ZEBRA_SET_TRACE3                       (LPC_GPIO2->FIOSET = (1<<3))
#define ZEBRA_CLR_TRACE3                       (LPC_GPIO2->FIOCLR = (1<<3))
#define ZEBRA_ON_TRACE3                       (LPC_GPIO2->FIOSET = (1<<3))
#define ZEBRA_OFF_TRACE3                       (LPC_GPIO2->FIOCLR = (1<<3))
#define ZEBRA_QON_TRACE3                      ((LPC_GPIO2->FIOPIN & (1<<3)) >> 3)
#define ZEBRA_GET_TRACE4                      ((LPC_GPIO2->FIOPIN & (1<<4)) >> 4)
#define ZEBRA_SET_TRACE4                       (LPC_GPIO2->FIOSET = (1<<4))
#define ZEBRA_CLR_TRACE4                       (LPC_GPIO2->FIOCLR = (1<<4))
#define ZEBRA_ON_TRACE4                       (LPC_GPIO2->FIOSET = (1<<4))
#define ZEBRA_OFF_TRACE4                       (LPC_GPIO2->FIOCLR = (1<<4))
#define ZEBRA_QON_TRACE4                      ((LPC_GPIO2->FIOPIN & (1<<4)) >> 4)
#define ZEBRA_GET_TRACE5                      ((LPC_GPIO2->FIOPIN & (1<<5)) >> 5)
#define ZEBRA_SET_TRACE5                       (LPC_GPIO2->FIOSET = (1<<5))
#define ZEBRA_CLR_TRACE5                       (LPC_GPIO2->FIOCLR = (1<<5))
#define ZEBRA_ON_TRACE5                       (LPC_GPIO2->FIOSET = (1<<5))
#define ZEBRA_OFF_TRACE5                       (LPC_GPIO2->FIOCLR = (1<<5))
#define ZEBRA_QON_TRACE5                      ((LPC_GPIO2->FIOPIN & (1<<5)) >> 5)
#define ZEBRA_GET_TRACE6                      ((LPC_GPIO2->FIOPIN & (1<<6)) >> 6)
#define ZEBRA_SET_TRACE6                       (LPC_GPIO2->FIOSET = (1<<6))
#define ZEBRA_CLR_TRACE6                       (LPC_GPIO2->FIOCLR = (1<<6))
#define ZEBRA_ON_TRACE6                       (LPC_GPIO2->FIOSET = (1<<6))
#define ZEBRA_OFF_TRACE6                       (LPC_GPIO2->FIOCLR = (1<<6))
#define ZEBRA_QON_TRACE6                      ((LPC_GPIO2->FIOPIN & (1<<6)) >> 6)
#define ZEBRA_GET_TRACE7                      ((LPC_GPIO2->FIOPIN & (1<<7)) >> 7)
#define ZEBRA_SET_TRACE7                       (LPC_GPIO2->FIOSET = (1<<7))
#define ZEBRA_CLR_TRACE7                       (LPC_GPIO2->FIOCLR = (1<<7))
#define ZEBRA_ON_TRACE7                       (LPC_GPIO2->FIOSET = (1<<7))
#define ZEBRA_OFF_TRACE7                       (LPC_GPIO2->FIOCLR = (1<<7))
#define ZEBRA_QON_TRACE7                      ((LPC_GPIO2->FIOPIN & (1<<7)) >> 7)
#define ZEBRA_GET_TRACE8                      ((LPC_GPIO2->FIOPIN & (1<<8)) >> 8)
#define ZEBRA_SET_TRACE8                       (LPC_GPIO2->FIOSET = (1<<8))
#define ZEBRA_CLR_TRACE8                       (LPC_GPIO2->FIOCLR = (1<<8))
#define ZEBRA_ON_TRACE8                       (LPC_GPIO2->FIOSET = (1<<8))
#define ZEBRA_OFF_TRACE8                       (LPC_GPIO2->FIOCLR = (1<<8))
#define ZEBRA_QON_TRACE8                      ((LPC_GPIO2->FIOPIN & (1<<8)) >> 8)
#define ZEBRA_GET_USB_CONNECT                 ((LPC_GPIO2->FIOPIN & (1<<9)) >> 9)
#define ZEBRA_SET_USB_CONNECT                  (LPC_GPIO2->FIOSET = (1<<9))
#define ZEBRA_CLR_USB_CONNECT                  (LPC_GPIO2->FIOCLR = (1<<9))
#define ZEBRA_ON_USB_CONNECT                  (LPC_GPIO2->FIOSET = (1<<9))
#define ZEBRA_OFF_USB_CONNECT                  (LPC_GPIO2->FIOCLR = (1<<9))
#define ZEBRA_QON_USB_CONNECT                 ((LPC_GPIO2->FIOPIN & (1<<9)) >> 9)
#define ZEBRA_GET_L14_BOOT_CONTROL            ((LPC_GPIO2->FIOPIN & (1<<10)) >> 10)
#define ZEBRA_SET_L14_BOOT_CONTROL             (LPC_GPIO2->FIOSET = (1<<10))
#define ZEBRA_CLR_L14_BOOT_CONTROL             (LPC_GPIO2->FIOCLR = (1<<10))
#define ZEBRA_ON_L14_BOOT_CONTROL             (LPC_GPIO2->FIOSET = (1<<10))
#define ZEBRA_OFF_L14_BOOT_CONTROL             (LPC_GPIO2->FIOCLR = (1<<10))
#define ZEBRA_QON_L14_BOOT_CONTROL            ((LPC_GPIO2->FIOPIN & (1<<10)) >> 10)
#define ZEBRA_GET_INT2_RX                     ((LPC_GPIO2->FIOPIN & (1<<11)) >> 11)
#define ZEBRA_SET_INT2_RX                      (LPC_GPIO2->FIOSET = (1<<11))
#define ZEBRA_CLR_INT2_RX                      (LPC_GPIO2->FIOCLR = (1<<11))
#define ZEBRA_ON_INT2_RX                      (LPC_GPIO2->FIOSET = (1<<11))
#define ZEBRA_OFF_INT2_RX                      (LPC_GPIO2->FIOCLR = (1<<11))
#define ZEBRA_QON_INT2_RX                     ((LPC_GPIO2->FIOPIN & (1<<11)) >> 11)
#define ZEBRA_GET_INT_TX                      ((LPC_GPIO2->FIOPIN & (1<<12)) >> 12)
#define ZEBRA_SET_INT_TX                       (LPC_GPIO2->FIOSET = (1<<12))
#define ZEBRA_CLR_INT_TX                       (LPC_GPIO2->FIOCLR = (1<<12))
#define ZEBRA_ON_INT_TX                       (LPC_GPIO2->FIOSET = (1<<12))
#define ZEBRA_OFF_INT_TX                       (LPC_GPIO2->FIOCLR = (1<<12))
#define ZEBRA_QON_INT_TX                      ((LPC_GPIO2->FIOPIN & (1<<12)) >> 12)
#define ZEBRA_GET_INT_RX                      ((LPC_GPIO2->FIOPIN & (1<<13)) >> 13)
#define ZEBRA_SET_INT_RX                       (LPC_GPIO2->FIOSET = (1<<13))
#define ZEBRA_CLR_INT_RX                       (LPC_GPIO2->FIOCLR = (1<<13))
#define ZEBRA_ON_INT_RX                       (LPC_GPIO2->FIOSET = (1<<13))
#define ZEBRA_OFF_INT_RX                       (LPC_GPIO2->FIOCLR = (1<<13))
#define ZEBRA_QON_INT_RX                      ((LPC_GPIO2->FIOPIN & (1<<13)) >> 13)
#define ZEBRA_GET_MATCH2P0                    ((LPC_GPIO4->FIOPIN & (1<<28)) >> 28)
#define ZEBRA_SET_MATCH2P0                     (LPC_GPIO4->FIOSET = (1<<28))
#define ZEBRA_CLR_MATCH2P0                     (LPC_GPIO4->FIOCLR = (1<<28))
#define ZEBRA_ON_MATCH2P0                     (LPC_GPIO4->FIOSET = (1<<28))
#define ZEBRA_OFF_MATCH2P0                     (LPC_GPIO4->FIOCLR = (1<<28))
#define ZEBRA_QON_MATCH2P0                    ((LPC_GPIO4->FIOPIN & (1<<28)) >> 28)
#define ZEBRA_GET_MATCH2P1                    ((LPC_GPIO4->FIOPIN & (1<<29)) >> 29)
#define ZEBRA_SET_MATCH2P1                     (LPC_GPIO4->FIOSET = (1<<29))
#define ZEBRA_CLR_MATCH2P1                     (LPC_GPIO4->FIOCLR = (1<<29))
#define ZEBRA_ON_MATCH2P1                     (LPC_GPIO4->FIOSET = (1<<29))
#define ZEBRA_OFF_MATCH2P1                     (LPC_GPIO4->FIOCLR = (1<<29))
#define ZEBRA_QON_MATCH2P1                    ((LPC_GPIO4->FIOPIN & (1<<29)) >> 29)

//************************************************************************
//***  Input Pin Info CSV file pinout.csv, printed below for reference:
//************************************************************************
//0001: ITEM,P176x,PORT,BIT,FUNC1,FUNC2,FUNC3,SIGNAL,FUNC,IN/OUT,MODE,OD,DEF,ACT
//0002: 6,0,0,RD1,TXD3,SDA1,PIC_TXD,1,1,,,,
//0003: 7,0,1,TD1,RXD3,SCL1,PIC_RXD,1,0,,,,
//0004: 8,0,2,TXD0,N/A,N/A,TXD1,1,0,,,,
//0005: 9,0,3,RXD0,N/A,N/A,RXD1,1,1,,,,
//0006: 1,0,4,I2SRX_CLK,RD2,CAP2.0,IR_SIG,0,1,,,,
//0007: 0,0,5,I2SRX_WS,TD2,CAP2.1,ST_LED2,0,0,,,0,1
//0008: 9,0,6,I2SRX_SDA,SSEL1,MAT2.0,ST_LED3,0,0,,,0,0
//0009: 8,0,7,I2STX_CLK,SCK1,MAT2.1,ST_LED4,0,0,,,0,0
//0010: 7,0,8,I2STX_WS,MISO1,MAT2.2,ST_LED5,0,0,,,0,0
//0011: 76,0,9,I2SRTX_SDA,MOSI1,MAT2.3,ST_LED6,0,0,,,0,0
//0012: 48,0,10,TXD2,SDA2,MAT3.0,SDA2,2,0,,,,
//0013: 49,0,11,RXD2,SCL2,MAT3.1,SCL2,2,0,,,,
//0014: N/A,0,12,N/A,N/A,N/A,,,,,,,
//0015: N/A,0,13,N/A,N/A,N/A,,,,,,,
//0016: N/A,0,14,N/A,N/A,N/A,,,,,,,
//0017: 62,0,15,TXD1,SCK0,SCK,SPI_CLK,3,,,,,
//0018: 63,0,16,RXD1,SSEL0,SSEL,SPI_CSEL,3,,,,,
//0019: 61,0,17,CTS1,MISO0,MISO,SPI_MISO,3,,,,,
//0020: 60,0,18,DCD1,MOSI0,MOSI,SPI_MOSI,3,,,,,
//0021: 59,0,19,DSR1,MCICLK,SDA1,SPI_HOLD,,,,,,
//0022: 58,0,20,DTR1,MSICMD,SCL1,MCU_RESET_OUT,,,,,,
//0023: 57,0,21,RI1,MCIPWR,RD1,GLOBAL_RESET,,,,,,
//0024: 56,0,22,RTS1,MCIDATA0,TD1,PIC_RESET,0,,,1,1,
//0025: 9,0,23,AD0.0,I2SRX_CLK,CAP3.0,MCU_3V3_EN,0,0,,,0,0
//0026: 8,0,24,AD0.1,I2SRX_WS,CAP3.1,MCU_1V8_EN,0,0,,,0,0
//0027: 7,0,25,AD0.2,I2SRX_SDA,TXD3,,,,,,,
//0028: 6,0,26,AD0.3,AOUT,RXD3,,,,,,,
//0029: 25,0,27,SDA0,N/A,N/A,SDA,1,,,,,
//0030: 24,0,28,SCL0,N/A,N/A,SCL,1,,,,,
//0031: 29,0,29,USB_D+1,N/A,N/A,USB_DP,0,,,,,
//0032: 30,0,30,USB_D-1,N/A,N/A,USB_DM,0,,,,,
//0033: N/A,0,31,N/A,N/A,N/A,,,,,,,
//0034: 95,1,0,ENET_TXD0,N/A,N/A,PB0,0,1,,,,0
//0035: 94,1,1,ENET_TXD1,N/A,N/A,PB1,0,1,,,,0
//0036: N/A,1,2,N/A,N/A,N/A,,,,,,,
//0037: N/A,1,3,N/A,N/A,N/A,,,,,,,
//0038: 93,1,4,ENET_TX_EN,N/A,N/A,PB2,0,1,,,,0
//0039: N/A,1,5,N/A,N/A,N/A,,,,,,,
//0040: N/A,1,6,N/A,N/A,N/A,,,,,,,
//0041: N/A,1,7,N/A,N/A,N/A,,,,,,,
//0042: 92,1,8,ENET_CRS,N/A,N/A,PB3,0,1,,,,0
//0043: 91,1,9,ENET_RXD0,N/A,N/A,PB4,0,1,,,,0
//0044: 90,1,10,ENET_RXD1,N/A,N/A,PB5,0,1,,,,0
//0045: N/A,1,11,N/A,N/A,N/A,,,,,,,
//0046: N/A,1,12,N/A,N/A,N/A,,,,,,,
//0047: N/A,1,13,N/A,N/A,N/A,,,,,,,
//0048: 89,1,14,ENET_RX_ER,N/A,N/A,S10_SW_ENABLE,0,1,,,,
//0049: 88,1,15,ENET_REF_CLK,N/A,N/A,,,,,,,
//0050: 87,1,16,ENET_MDC,N/A,N/A,AUX2,0,0,,,,
//0051: 86,1,17,ENET_MDIO,N/A,N/A,AUX1,0,0,,,,
//0052: 32,1,18,USP_UP_LED,PWM1.1,CAP1.0,USP_UP_LED,0,0,,,,
//0053: 33,1,19,USB_TX_E1,USB_PPWR1,CAP1.1,CHAN_SEL,0,0,,,,
//0054: 34,1,20,USB_TX_DP1,PWM1.2,SCK0,SHUNT_CH1,0,0,,,0,0
//0055: 35,1,21,USB_TX_DM1,PWM1.3,SSEL0,SHUNT_CH2,0,0,,,1,0
//0056: 36,1,22,USB_RCV1,USB_PWRD1,MAT1.0,,,,,,,
//0057: 37,1,23,USB_RX_DP1,PWM1.4,MISO0,PWM_GCA1,0,1,,,,
//0058: 38,1,24,USB_RX_DM1,PWM1.5,MOSI0,PWM_GCA2,0,1,,,,
//0059: 39,1,25,USB_LS1,USB_HSTEN1,MAT1.1,,,,,,,
//0060: 40,1,26,USB_SSPND1,PWM1.6,CAP0.0,,,,,,,
//0061: 43,1,27,USB_INT1,USB_OVRCR1,CAP0.1,,,,,,,
//0062: 44,1,28,USB_SCL1,PCAP1.0,MAT0.0,,,,,,,
//0063: 45,1,29,USB_SDA1,PCAP1.1,MAT0.1,,,,,,,
//0064: 21,1,30,N/A,VBUS,AD0.4,MCU_VBUS,0,,,,,
//0065: 20,1,31,N/A,SCK1,AD0.5,PIC_ERR,0,1,,,,
//0066: 75,2,0,PWM1.1,TXD1,TRACECLK,TRACE0,0,1,,,,
//0067: 74,2,1,PWM1.2,RXD1,PIPESTAT0,TRACE1,0,1,,,,
//0068: 73,2,2,PWM1.3,CTS1,PIPESTAT1,TRACE2,0,1,,,,
//0069: 70,2,3,PWM1.4,DCD1,PIPESTAT2,TRACE3,0,1,,,,
//0070: 69,2,4,PWM1.5,DSR1,TRACESYNC,TRACE4,0,1,,,,
//0071: 68,2,5,PWM1.6,DTR1,TRACEPKT0,TRACE5,0,1,,,,
//0072: 67,2,6,PCAP1.0,RI1,TRACEPKT1,TRACE6,0,1,,,,
//0073: 66,2,7,RD2,RTS1,TRACEPKT2,TRACE7,0,1,,,,
//0074: 65,2,8,TD2,TXD2,TRACEPKT3,TRACE8,0,1,,,,
//0075: 64,2,9,USB_CONNECT,RXD2,EXTIN0,USB_CONNECT,0,,,,,
//0076: 53,2,10,EINT0,N/A,N/A,L14_BOOT_CONTROL,0,1,,,,
//0077: 52,2,11,EINT1,MCIDAT1,I2STX_CLK,INT2_RX,0,1,,,,
//0078: 51,2,12,EINT2,MCIDAT2,I2STX_WS,INT_TX,0,1,,,,
//0079: 50,2,13,EINT3,MCIDAT3,I2STX_SDA,INT_RX,0,1,,,,
//0080: N/A,2,14,N/A,N/A,N/A,,,,,,,
//0081: N/A,2,15,N/A,N/A,N/A,,,,,,,
//0082: N/A,2,16,N/A,N/A,N/A,,,,,,,
//0083: N/A,2,17,N/A,N/A,N/A,,,,,,,
//0084: N/A,2,18,N/A,N/A,N/A,,,,,,,
//0085: N/A,2,19,N/A,N/A,N/A,,,,,,,
//0086: N/A,2,20,N/A,N/A,N/A,,,,,,,
//0087: N/A,2,21,N/A,N/A,N/A,,,,,,,
//0088: N/A,2,22,N/A,N/A,N/A,,,,,,,
//0089: N/A,2,23,N/A,N/A,N/A,,,,,,,
//0090: N/A,2,24,N/A,N/A,N/A,,,,,,,
//0091: N/A,2,25,N/A,N/A,N/A,,,,,,,
//0092: N/A,2,26,N/A,N/A,N/A,,,,,,,
//0093: N/A,2,27,N/A,N/A,N/A,,,,,,,
//0094: N/A,2,28,N/A,N/A,N/A,,,,,,,
//0095: N/A,2,29,N/A,N/A,N/A,,,,,,,
//0096: N/A,2,30,N/A,N/A,N/A,,,,,,,
//0097: N/A,2,31,N/A,N/A,N/A,,,,,,,
//0098: N/A,3,0,N/A,N/A,N/A,,,,,,,
//0099: N/A,3,1,N/A,N/A,N/A,,,,,,,
//0100: N/A,3,2,N/A,N/A,N/A,,,,,,,
//0101: ,N/A,3,3,N/A,N/A,N/A,,,,,,,
//0102: ,N/A,3,4,N/A,N/A,N/A,,,,,,,
//0103: ,N/A,3,5,N/A,N/A,N/A,,,,,,,
//0104: ,N/A,3,6,N/A,N/A,N/A,,,,,,,
//0105: ,N/A,3,7,N/A,N/A,N/A,,,,,,,
//0106: ,N/A,3,8,N/A,N/A,N/A,,,,,,,
//0107: ,N/A,3,9,N/A,N/A,N/A,,,,,,,
//0108: ,N/A,3,10,N/A,N/A,N/A,,,,,,,
//0109: ,N/A,3,11,N/A,N/A,N/A,,,,,,,
//0110: ,N/A,3,12,N/A,N/A,N/A,,,,,,,
//0111: ,N/A,3,13,N/A,N/A,N/A,,,,,,,
//0112: ,N/A,3,14,N/A,N/A,N/A,,,,,,,
//0113: ,N/A,3,15,N/A,N/A,N/A,,,,,,,
//0114: ,N/A,3,16,N/A,N/A,N/A,,,,,,,
//0115: ,N/A,3,17,N/A,N/A,N/A,,,,,,,
//0116: ,N/A,3,18,N/A,N/A,N/A,,,,,,,
//0117: ,N/A,3,19,N/A,N/A,N/A,,,,,,,
//0118: ,N/A,3,20,N/A,N/A,N/A,,,,,,,
//0119: ,N/A,3,21,N/A,N/A,N/A,,,,,,,
//0120: ,N/A,3,22,N/A,N/A,N/A,,,,,,,
//0121: ,N/A,3,23,N/A,N/A,N/A,,,,,,,
//0122: ,N/A,3,24,N/A,N/A,N/A,,,,,,,
//0123: ,27,3,25,N/A,MAT0.0,PWM1.2,,,,,,,
//0124: ,26,3,26,N/A,MAT0.1,PWM1.3,,,,,,,
//0125: ,N/A,3,27,N/A,N/A,N/A,,,,,,,
//0126: ,N/A,3,28,N/A,N/A,N/A,,,,,,,
//0127: ,N/A,3,29,N/A,N/A,N/A,,,,,,,
//0128: ,N/A,3,30,N/A,N/A,N/A,,,,,,,
//0129: ,N/A,3,31,N/A,N/A,N/A,,,,,,,
//0130: ,N/A,4,0,N/A,N/A,N/A,,,,,,,
//0131: ,N/A,4,1,N/A,N/A,N/A,,,,,,,
//0132: ,N/A,4,2,N/A,N/A,N/A,,,,,,,
//0133: ,N/A,4,3,N/A,N/A,N/A,,,,,,,
//0134: ,N/A,4,4,N/A,N/A,N/A,,,,,,,
//0135: ,N/A,4,5,N/A,N/A,N/A,,,,,,,
//0136: ,N/A,4,6,N/A,N/A,N/A,,,,,,,
//0137: ,N/A,4,7,N/A,N/A,N/A,,,,,,,
//0138: ,N/A,4,8,N/A,N/A,N/A,,,,,,,
//0139: ,N/A,4,9,N/A,N/A,N/A,,,,,,,
//0140: ,N/A,4,10,N/A,N/A,N/A,,,,,,,
//0141: ,N/A,4,11,N/A,N/A,N/A,,,,,,,
//0142: ,N/A,4,12,N/A,N/A,N/A,,,,,,,
//0143: ,N/A,4,13,N/A,N/A,N/A,,,,,,,
//0144: ,N/A,4,14,N/A,N/A,N/A,,,,,,,
//0145: ,N/A,4,15,N/A,N/A,N/A,,,,,,,
//0146: ,N/A,4,16,N/A,N/A,N/A,,,,,,,
//0147: ,N/A,4,17,N/A,N/A,N/A,,,,,,,
//0148: ,N/A,4,18,N/A,N/A,N/A,,,,,,,
//0149: ,N/A,4,19,N/A,N/A,N/A,,,,,,,
//0150: ,N/A,4,20,N/A,N/A,N/A,,,,,,,
//0151: ,N/A,4,21,N/A,N/A,N/A,,,,,,,
//0152: ,N/A,4,22,N/A,N/A,N/A,,,,,,,
//0153: ,N/A,4,23,N/A,N/A,N/A,,,,,,,
//0154: ,N/A,4,24,N/A,N/A,N/A,,,,,,,
//0155: ,N/A,4,25,N/A,N/A,N/A,,,,,,,
//0156: ,N/A,4,26,N/A,N/A,N/A,,,,,,,
//0157: ,N/A,4,27,N/A,N/A,N/A,,,,,,,
//0158: ,82,4,28,N/A,MAT2.0,TXD3,MATCH2P0,2,0,,,,
//0159: ,85,4,29,N/A,MAT2.1,RXD3,MATCH2P1,2,0,,,,
//0160: ,N/A,4,30,N/A,N/A,N/A,,,,,,,
//0161: ,N/A,4,31,N/A,N/A,N/A,,,,,,,
//0162: ,1,99,0,TDO,,,,,,,,,
//0163: ,2,99,1,TDI,,,,,,,,,
//0164: ,3,99,2,TMS,,,,,,,,,
//0165: ,4,99,3,TRST,,,,,,,,,
//0166: ,5,99,4,TCK,,,,,,,,,
//0167: ,100,99,5,RTCK,,,,,,,,,
//0168: ,14,99,6,RSTOUT,,,,,,,,,
//0169: ,17,99,7,EXTRST,,,,,,,,,
//0170: ,22,99,8,OSCIN,,,,,,,,,
//0171: ,23,99,9,OSCOUT,,,,,,,,,
//0172: ,16,99,10,XOSCIN,,,,,,,,,
//0173: ,18,99,11,XOSCOUT,,,,,,,,,
//0174: ,31,99,12,GND,,,,,,,,,
//0175: ,41,99,13,GND,,,,,,,,,
//0176: ,55,99,14,GND,,,,,,,,,
//0177: ,72,99,15,GND,,,,,,,,,
//0178: ,83,99,16,GND,,,,,,,,,
//0179: ,97,99,17,GND,,,,,,,,,
//0180: ,11,99,18,AGND,,,,,,,,,
//0181: ,28,99,19,V3P3,,,,,,,,,
//0182: ,54,99,20,V3P3,,,,,,,,,
//0183: ,71,99,21,V3P3,,,,,,,,,
//0184: ,96,99,22,V3P3,,,,,,,,,
//0185: ,N/A,99,23,V3P3DCC,,,,,,,,,
//0186: ,42,99,24,V3P3DCC,,,,,,,,,
//0187: ,84,99,25,V3P3DCC,,,,,,,,,
//0188: ,10,99,26,VA3P3,,,,,,,,,
//0189: ,12,99,27,VREF,,,,,,,,,
//0190: ,15,99,28,GND,,,,,,,,,
//0191: ,19,99,29,VBAT,,,,,,,,,
//0192: ,,,,,,,,,,,,,
//************************************************************************
//***  END OF FILE pinout.csv
//************************************************************************
